controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

back_office:
    path: /back-office
    controller: App\Controller\BackOfficeController::index

edit_user:
    path: /back-office/users/{id}/edit
    controller: App\Controller\BackOfficeController::editUser

delete_user:
    path: /back-office/users/{id}/delete
    controller: App\Controller\BackOfficeController::deleteUser